const motion=[
{id:'visual_music_orbit',name:'Visual Music Orbit',principle:'音楽構造を幾何形態の軌道・反復・色変化へ変換',timing:'拍単位の反復と漸進変化',camera:'固定または正投影',moves:['円・楕円の軌道','スケールの呼吸','拍同期の色面転換']},
{id:'direct_film_energy',name:'Direct Film Energy',principle:'素材へ直接刻むような線・傷・色の運動',timing:'不均一な短い衝撃',camera:'フィルム面固定',moves:['スクラッチ線','飛沫','手描きストローク']},
{id:'synchromy_system',name:'Synchromy System',principle:'音・図形・速度を同じ規則で同期',timing:'加速・定速・減速を明示',camera:'固定',moves:['セル分裂','音階と色の対応','速度曲線']},
{id:'computational_harmony',name:'Computational Harmony',principle:'数学的周期と位相差から調和する運動を生成',timing:'長い周期と位相ずれ',camera:'中心軸固定',moves:['同心回転','リサージュ軌道','収束と発散']},
{id:'title_sequence_tension',name:'Title Sequence Tension',principle:'単一記号と切断的編集で物語の緊張を圧縮',timing:'硬いカット、2〜4秒単位',camera:'グラフィック面固定',moves:['分断線','切り抜き形状','段階的タイトル']},
{id:'kinetic_typography_system',name:'Kinetic Typography System',principle:'文字を空間・速度・視点で探索可能な情報構造にする',timing:'読み取り速度に合わせる',camera:'情報空間を前進・旋回',moves:['文字の奥行き配置','ズーム階層','情報群の再整列']},
{id:'interface_emergence',name:'Interface Emergence',principle:'小さな要素のルールから全体の形が立ち上がる',timing:'入力→反応→収束',camera:'固定または追従',moves:['エージェント群','軌跡の蓄積','自己整列']},
{id:'organic_morph_brand',name:'Organic Morph Brand',principle:'プロダクト形状を有機的変形と精密な材質でブランド化',timing:'滑らかなイーズ',camera:'マクロからワイド',moves:['材質変形','押し出し','シームレスループ']},
{id:'tactile_surreal_3d',name:'Tactile Surreal 3D',principle:'触れられそうな3D素材と小さな超現実性を組み合わせる',timing:'期待から短い変化',camera:'商品撮影的ドリー',moves:['柔らかな物体','粒子凝集','質感転換']},
{id:'graphic_character_burst',name:'Graphic Character Burst',principle:'強いグラフィック形状とキャラクター的運動で感情を作る',timing:'スナッピー、オーバーシュート',camera:'平面中心',moves:['弾む形','伸縮','マッチカット']},
{id:'cinematic_hard_surface',name:'Cinematic Hard Surface',principle:'硬質な構造物・建築を映画的照明と編集で見せる',timing:'緩い導入→強いカット→余韻',camera:'低い視点、長焦点',moves:['構造展開','光の走査','霧中の移動']},
{id:'procedural_spectral',name:'Procedural Spectral',principle:'光学・レーザー・干渉・データをスペクトル現象へ変換',timing:'パルス、走査、波形同期',camera:'精密ドリー',moves:['光線走査','干渉縞','スペクトル分解']},
{id:'architectural_transformation',name:'Architectural Transformation',principle:'建築・都市・グリッドを変形させ空間をメッセージにする',timing:'構築→変形→再構築',camera:'建築的ワイド',moves:['都市ブロック展開','面の反転','地図から建築へ']},
{id:'monumental_simulation',name:'Monumental Simulation',principle:'巨大スケールと日常的対象の対比で一瞬の物語を作る',timing:'静かな観察＋単一の大きな事象',camera:'超ワイド、ゆっくりプッシュ',moves:['巨大構造物','環境シミュレーション','スケール対比']}
];
const formats={reels:{w:1080,h:1920,aspect:'9:16',safe:'上250 / 下340 / 左右80px'},story:{w:1080,h:1920,aspect:'9:16',safe:'上250 / 下300 / 左右72px'},x_vertical:{w:1080,h:1920,aspect:'9:16',safe:'上120 / 下180 / 左右72px'},x_landscape:{w:1920,h:1080,aspect:'16:9',safe:'上下90 / 左右96px'},square:{w:1080,h:1080,aspect:'1:1',safe:'上72 / 下96 / 左右72px'}};
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function recipe(){const seed=document.querySelector('#seed').value||Date.now().toString();const f=formats[document.querySelector('#format').value];const m=motion[hash(seed)%motion.length];const seconds=Math.max(3,Math.min(60,+document.querySelector('#seconds').value||10));const count=Math.max(1,Math.min(4,+document.querySelector('#outputs').value||1));const shots=seconds<=6?3:seconds<=15?5:8;const theme=document.querySelector('#theme').value;const headline=document.querySelector('#headline').value;const board=Array.from({length:shots},(_,i)=>({shot:i+1,start:+(i*seconds/shots).toFixed(2),end:+((i+1)*seconds/shots).toFixed(2),role:i===0?'HOOK':i===shots-1?'CTA':'DEVELOP'}));const prompt=`Create an original ${f.aspect} ${seconds}-second social video, ${f.w}x${f.h}, 30fps. Theme: ${theme}. Headline: ${headline}. Motion principle: ${m.principle}. Timing: ${m.timing}. Camera: ${m.camera}. Animation: ${m.moves.join(', ')}. Keep essential text in safe area (${f.safe}). Use one coherent limited palette, preserve brand assets, avoid creator names, direct imitation, fabricated metrics, client logos, generic AI brains and meaningless neon.`;return{seed,outputs:count,format:f,motion:m,storyboard:board,productionPrompt:prompt,limitNotice:'実レンダリングの秒数・解像度・本数は接続モデルと契約プランに依存。未確認値は VERIFY_IN_ACCOUNT。'}}
document.querySelector('#go').onclick=()=>{const r=recipe();document.querySelector('#result').innerHTML=`<h2>${r.motion.name}</h2><div class="grid"><div class="card"><b>FORMAT</b><p>${r.format.w}×${r.format.h} / ${r.format.aspect}</p></div><div class="card"><b>MOTION</b><p>${r.motion.principle}</p></div><div class="card"><b>LIMITS</b><p>${r.limitNotice}</p></div></div><h3>STORYBOARD</h3><pre>${JSON.stringify(r.storyboard,null,2)}</pre><h3>PRODUCTION PROMPT</h3><pre>${r.productionPrompt}</pre><button id="copy">COPY RECIPE</button>`;document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(JSON.stringify(r,null,2))};